/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.gradle.tamplate;

import org.junit.Test;
import static org.junit.Assert.*;

public class DummyTest {
    @Test public void testDummy() {
        assertTrue(true);
    }
}
