/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.gradle.tamplate;

import org.junit.Test;

import static org.junit.Assert.*;

public class DummyTest {
	
	private Main main;
    
	public class MainTest {
	
		@Test public void mainStartTest() {
			main = new Main();
			assertNotNull(main.getPrimaryStage());
			
		}
	}
}
